### ISSUE TITLE
2.0.6 fails to build on rawhide, gcc 4.6.0. patch included

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dirkvdb/ffmpegthumbnailer#83]
```
What steps will reproduce the problem?
1. Try to compile on fedora rawhide
2. Fail with libffmpegthumbnailer/filmstripfilter.cpp:27:16 error: 'NULL' was 
not declared in this scope
3.

What is the expected output? What do you see instead?
Code should compile

What version of the product are you using? On what operating system?
Fedora rawhide x86_64

Please provide any additional information below.
missing include in filmstripfilter.ccp? #include <stddef.h> fixes this and the 
code then compiles.
Attaching a patch.

```

Original issue reported on code.google.com by `magnus.t...@gmail.com` on 13 Feb 2011 at 12:53

Attachments:
- [ffmpegthumbnailer-null.patch](https://storage.googleapis.com/google-code-attachments/ffmpegthumbnailer/issue-83/comment-0/ffmpegthumbnailer-null.patch)
