### ISSUE TITLE
Fails to build with GCC 4.4: missing #include

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dirkvdb/ffmpegthumbnailer#17]
```
Hi,

A Debian user reported that ffmpegthumbnailer 1.3.0 (afaik trunk is
affected as well) fails to build with GCC 4.4. It seems that GCC 4.4
cleaned up some more C++ headers, so you always have to #include headers
directly and cannot rely for things to be included indirectly.

> libtool: compile:  g++ -DPACKAGE_NAME=\"ffmpegthumbnailer\"
-DPACKAGE_TARNAME=\"ffmpegthumbnailer\" -DPACKAGE_VERSION=\"1.3.0\"
"-DPACKAGE_STRING=\"ffmpegthumbnailer 1.3.0\"" -DPACKAGE_BUGREPORT=\"\"
-DPACKAGE=\"ffmpegthumbnailer\" -DVERSION=\"1.3.0\" -DSTDC_HEADERS=1
-DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1
-DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1
-DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\"
-DSTDC_HEADERS=1 -DHAVE_INTTYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_JPEGLIB_H=1
-DHAVE_FFMPEG_AVCODEC_H=1 -DHAVE_FFMPEG_AVFORMAT_H=1
-DHAVE_FFMPEG_AVUTIL_H=1 -DHAVE_FFMPEG_SWSCALE_H=1 -I. -g -O2 -c
jpegwriter.cpp  -fPIC -DPIC -o .libs/jpegwriter.o
> jpegwriter.cpp: In constructor 'JpegWriter::JpegWriter(const std::string&)':
> jpegwriter.cpp:44: error: 'fopen' was not declared in this scope
> jpegwriter.cpp: In destructor 'virtual JpegWriter::~JpegWriter()':
> jpegwriter.cpp:74: error: 'fclose' was not declared in this scope
> make[3]: *** [jpegwriter.lo] Error 1
> make[3]: Leaving directory
`/build/tbm/ffmpegthumbnailer-1.3.0/src/libffmpegthumbnailer'

He proposed the following patch, which should fix this issue:

--- src/libffmpegthumbnailer/jpegwriter.cpp~    2009-01-04
08:47:08.000000000 +0000
+++ src/libffmpegthumbnailer/jpegwriter.cpp     2009-01-04
08:47:16.000000000 +0000
@@ -16,6 +16,7 @@

 #include "jpegwriter.h"
 #include <stdexcept>
+#include <cstdio>
 #include <cstring>
 #include <assert.h>
 #include <algorithm>

Thanks!
```

Original issue reported on code.google.com by `mrpo...@gmail.com` on 4 Jan 2009 at 10:09
