### ISSUE TITLE
Release 2.0.6 doesn't compile on mandriva 2012.0 (cooker) + gcc 4.6.1

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dirkvdb/ffmpegthumbnailer#86]
```
What steps will reproduce the problem?
1.
gcc --version
gcc (GCC) 4.6.1 20110715 (Mandriva)
Copyright © 2011 Free Software Foundation, Inc.
Ce logiciel est libre; voir les sources pour les conditions de copie.  Il n'y a 
PAS
GARANTIE; ni implicite pour le MARCHANDAGE ou pour un BUT PARTICULIER.


2. configure
3. make

a compilation error occurs : 
libffmpegthumbnailer/filmstripfilter.cpp: In function ‘const uint8_t* 
ffmpegthumbnailer::determineFilmStrip(uint32_t, uint32_t&, uint32_t&)’:
libffmpegthumbnailer/filmstripfilter.cpp:27:16: erreur: ‘NULL’ was not 
declared in this scope


adding #include <stdlib.h> fixes the problem
```

Original issue reported on code.google.com by `ane.o.n...@gmail.com` on 19 Jul 2011 at 5:22
